# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvar < Formula
  desc "Terraform's variable definitions template generator."
  homepage "https://github.com/shihanng/tfvar"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/shihanng/tfvar/releases/download/v0.8.0/tfvar_darwin_arm64.tar.gz"
      sha256 "4caf7032deccc73235ab9289702642b24cbe93133e4dc2d43bcc1c64c232dd17"

      def install
        bin.install Dir['tfvar']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/tfvar/releases/download/v0.8.0/tfvar_darwin_amd64.tar.gz"
      sha256 "1c6d78c581e7ecf3501a80c392c14822804956ab84de1f8e896b3e6356cb3f43"

      def install
        bin.install Dir['tfvar']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/tfvar/releases/download/v0.8.0/tfvar_linux_amd64.tar.gz"
      sha256 "a65477a5850bd18bdb994b56414c0bb09d6c9373d5f9ca60cd8aba34f37bc660"

      def install
        bin.install Dir['tfvar']
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/shihanng/tfvar/releases/download/v0.8.0/tfvar_linux_armv6.tar.gz"
      sha256 "f717b075748319f316951a4a03799a42814bdb77952ec1cb0fc723260537cfce"

      def install
        bin.install Dir['tfvar']
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shihanng/tfvar/releases/download/v0.8.0/tfvar_linux_arm64.tar.gz"
      sha256 "fb31a216a392fd42069a5b704cccf1f47b1d7e59c098323755ff7a1f603bbedb"

      def install
        bin.install Dir['tfvar']
      end
    end
  end

  test do
    system "#{bin}/tfvar"
  end
end
