# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvar < Formula
  desc "Terraform's variable definitions template generator."
  homepage "https://github.com/shihanng/tfvar"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shihanng/tfvar/releases/download/v0.2.0/tfvar_darwin_amd64.tar.gz"
    sha256 "84bcc54a31508f19310f958605a45b037ac95376aa7a2760528e1a1bb9fefd85"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/tfvar/releases/download/v0.2.0/tfvar_linux_amd64.tar.gz"
      sha256 "c95f32762a8d34228acecb2a7899f2023dcce9bd043baeb9207f884741be06b2"
    end
  end

  def install
    bin.install Dir['tfvar']
  end

  test do
    system "#{bin}/tfvar"
  end
end
