# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfvar < Formula
  desc "Terraform's variable definitions template generator."
  homepage "https://github.com/shihanng/tfvar"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/tfvar/releases/download/v0.6.0/tfvar_darwin_amd64.tar.gz"
      sha256 "4bb10526c646a3e705f5e3cea83ea1f8c5bd034f6028227580fc9dcbb3b483c8"

      def install
        bin.install Dir['tfvar']
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shihanng/tfvar/releases/download/v0.6.0/tfvar_darwin_arm64.tar.gz"
      sha256 "3a03db1f3f7067c1d40fde9012b22e8a9d1af5890d4fef49f8edd6d622f25066"

      def install
        bin.install Dir['tfvar']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/tfvar/releases/download/v0.6.0/tfvar_linux_amd64.tar.gz"
      sha256 "eff5c71c01cfe6d41491c7fc3300bc797d48ca4c4c0480b7b5eb884c889172ac"

      def install
        bin.install Dir['tfvar']
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/shihanng/tfvar/releases/download/v0.6.0/tfvar_linux_armv6.tar.gz"
      sha256 "9b8962d80969b3f764722fa913010dca9fb45b4c501fae4ddf1bb6c8d8c2c939"

      def install
        bin.install Dir['tfvar']
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shihanng/tfvar/releases/download/v0.6.0/tfvar_linux_arm64.tar.gz"
      sha256 "32ea8fcb6ee21c83d55f3b526efbb7c185f8d33bde7f1dd56da45bf37fbeac1e"

      def install
        bin.install Dir['tfvar']
      end
    end
  end

  test do
    system "#{bin}/tfvar"
  end
end
